// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKPbgnOykKP71IJgG1sViyzZRzKhboBf8',
    appId: '1:291925528153:android:f01b349dc0266b3b26eb48',
    messagingSenderId: '291925528153',
    projectId: 'numbersapk',
    storageBucket: 'numbersapk.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7h-W9xpKesSWoIyYHvDxbX_QcirAehlw',
    appId: '1:291925528153:web:82ac5c9dd5c6a95126eb48',
    messagingSenderId: '291925528153',
    projectId: 'numbersapk',
    authDomain: 'numbersapk.firebaseapp.com',
    storageBucket: 'numbersapk.firebasestorage.app',
    measurementId: 'G-K3MJZ39DEJ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8SXgIWAuu1ijUrgpIAqTsAF6VM5TDsRg',
    appId: '1:291925528153:ios:22e41b5c0d97672326eb48',
    messagingSenderId: '291925528153',
    projectId: 'numbersapk',
    storageBucket: 'numbersapk.firebasestorage.app',
    iosClientId: '291925528153-gm2ebqfq0qemivlvcth037usa1tgrhi0.apps.googleusercontent.com',
    iosBundleId: 'com.jeopardyapps.numbers',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8SXgIWAuu1ijUrgpIAqTsAF6VM5TDsRg',
    appId: '1:291925528153:ios:22e41b5c0d97672326eb48',
    messagingSenderId: '291925528153',
    projectId: 'numbersapk',
    storageBucket: 'numbersapk.firebasestorage.app',
    iosClientId: '291925528153-gm2ebqfq0qemivlvcth037usa1tgrhi0.apps.googleusercontent.com',
    iosBundleId: 'com.jeopardyapps.numbers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7h-W9xpKesSWoIyYHvDxbX_QcirAehlw',
    appId: '1:291925528153:web:da17be8d1347b86826eb48',
    messagingSenderId: '291925528153',
    projectId: 'numbersapk',
    authDomain: 'numbersapk.firebaseapp.com',
    storageBucket: 'numbersapk.firebasestorage.app',
    measurementId: 'G-KCHDTXC8YY',
  );
}
